compatibility_date = "2023-03-01"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "myapp"
database_id = "b6d2c484-33ac-4a85-951a-ffde20e1e18f"
preview_database_id = "DB"
